### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by nozpheratu** [agilecrm/rest-api#1]
The header below https://github.com/agilecrm/rest-api#44-get-the-list-of-tasks-of-current-user should probably read:
### dev/api/tasks/my/tasks

But currently reads:

**Comment by graut** [comment]
Updated with correct contents. 
https://github.com/agilecrm/rest-api#44-get-the-list-of-tasks-of-current-user

**Comment by ranjanagilecrm** [comment]
Hi @nozpheratu,

Now the section reads as below for the corresponding Tasks API:  

https://github.com/agilecrm/rest-api#51-get-the-list-of-pending-tasks-depending-on-the-number-of-pending-days

**dev/api/tasks/pending/{num-days}**

Please let us know in case need further information.
