### ISSUE TITLE
Unable to retrieve companies using dev/api/contacts/search/email

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#10]
When I submit the email of a COMPANY instead of a PERSON using dev/api/contacts/search/email I receive null (I'm using JSON as output) in response, although it is present using the UI

**Comment by nicoolas25** [comment]
+1

**Comment by ranjanagilecrm** [comment]
Hi @nicoolas25 ,

We don't have any API to retrieve the company details while searching with email directly as we are doing with contacts.

But there is an alternative API to retrieve the company details for search as mentioned below : 

Request : 
https://{domain}.agilecrm.com/core/api/search/seachlist?q={company-id}&type=company
Method : GET
Accept : application/json
Content-Type: application/json

**Comment by andreafdaf** [comment]
Finally! It was about time! Thanks
