### ISSUE TITLE
When using JSON stringified fields should be returned parsed

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#11]
There is no point in returning a JSON object where some fields are... stringified JSON

Of course this is a must when using XML but if a client asks for the JSON output those fields should be parsed

**Comment by ranjanagilecrm** [comment]
Hi @andreafdaf ,

Thanks  for your suggestion. It'll be better to have a look if you can provide some examples.

**Comment by andreafdaf** [comment]
For example, I just requested a contact and the address property looks like this:
```javascript
{
  type: 'SYSTEM',
  name: 'address',
  subtype: 'home',
  value: '{"zip":"12345","address":"Via Roma 44","state":"Piemonte","countryname":"Italy","city":"Torino","country":"IT"}'
}
```

I used this small nodejs script, try something like it and you'll see that address.value is a string:
```
const Agile = require('agile_crm')
const agile_contacts = (new Agile("bla", "blabla", "bla@blabla.it")).contactAPI

async function test_stringified() {
  const data = await agile_contacts.getContactByEmail('me@adf.ninja')
  const address = data.properties.find((o) => o.name === 'address')
  console.info(typeof address.value) // prints "string"
}

test_stringified()
```

I would be expecting it to be an object, wouldn't you?
