### ISSUE TITLE
Suggestion: add tags based on id

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#14]
We can add tags to a contact based on email with
```
dev/api/contacts/email/tags/add
```
But it's not possible to do it using the contact ID, so if a contact doesn't have an email the only way to add a tag is to fetch the contact and update it... but adding a tag to the tags array and updating doesn't always work as one expects (it happened to me, sometimes if added this way the tag is visible only in the table view and disappears when inside the contact's page)

**Comment by graut** [comment]
This issue is resolved.

https://github.com/agilecrm/rest-api#18-update-tags-value-by-id

**Comment by andreafdaf** [comment]
thanks for listening! issue closed :+1:
