### ISSUE TITLE
Server error on GET of various assets

### ISSUE THREAD

**Issue by clintonskakun** [agilecrm/rest-api#18]
I'm getting this for some of my clients:

<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>500 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>

Will just happen randomly. Looks like it also happens when the server is under too much of a load. However, it also happens when I haven't been hitting the server very often as well.

Was hoping someone could address this. Maybe it's a common bug. I'm using Accept application/json and content type json for the curl requests. Works most of the time for contact fetches. Pulling in things like notes, tasks, etc. causes this a lot though.

**Comment by graut** [comment]
Hi @clintonskakun ,

Could you please share some get api calls you are using for client purpose. We will check from our end .If this fetch cause issue we should definitely get this issue,But we did not get any issue. Please share your domain also so we can check logs too.

Thanks

**Comment by clintonskakun** [comment]
I found the bug, it was associated with #20 closing this one.
