### ISSUE TITLE
Standardized messages for failure/success

### ISSUE THREAD

**Issue by emorling** [agilecrm/rest-api#19]
E.g. List of campaigns dev/api/workflows
simply sends a response "Sucesses"
Which also is misspelled

**Comment by clintonskakun** [comment]
I agree. There have been times when I get html output for 500 errors which gives me no hint on how to fix the problem. Having 100% JSON output at all times is a safe bet, even when error codes are consistent.

**Comment by ranjanagilecrm** [comment]
Hi @emorling & @ghost,

Now you can get the list of campaigns in the form of JSON data in the response for the status code 200.

We are giving 100% JSON output in the response for every API call you make.
