### ISSUE TITLE
contacts/companies does not work with cursor

### ISSUE THREAD

**Issue by clintonskakun** [agilecrm/rest-api#20]
When you do a simple call to the contacts/companies endpoint it returns successfully:

curl  -s -w "%{http_code}"  -H "Accept: application/json"  -u y:x https://x.agilecrm.com/dev/api/contacts/companies?page_size=25

However, when trying to run a call on the next page it gives me a 500 server error.

curl  -s -w "%{http_code}"  -H "Accept: application/json"  -u y:x https://x.agilecrm.com/dev/api/contacts/companies?page_size=25&cursor=CjwSNmoRc35hZ2lsZS1jcm0tY2xvdWRyFAsSB0NvbnRhY3QYgICAwNDBhwgMogEKZ2V0d29ya2VycxgAIAA

**Comment by graut** [comment]
Hi @clintonskakun,

Companies cursor is working fine from our end.
If you provide wrong cursor then you will get 500 server error.
First time when you are fetching companies with size 20, please don't provide any cursor.
Once you will get 20 companies, 20th company has the cursor so get the cursor from 20th company and for next time query to get other 20 companies use this cursor.
So at each 20 companies unique cursor will be produce and you need to get that cursor and need to use for further fetching data.

Thanks

**Comment by clintonskakun** [comment]
I'm going to close this since it seems the docs have been updated.
