### ISSUE TITLE
Associate user with company

### ISSUE THREAD

**Issue by arekPien** [agilecrm/rest-api#22]
Hey,
I have some troubles to correctly and satisfy integrate with your platform, exactly I have some issue with linking contact - company.

Could you add endpoint to edit contact's company id?
Currently, it is possible to define only during creation of the user which will cause that I can not add some of my users to Agile Crm.

Good thing would be to give ability to define list of user' id belong to company where company is creating.

It is my last point from my wish list and probably impossible that would be nice to have ability to link contact to many companies.

Cheers

**Comment by graut** [comment]
Hi @arekpien,

We can achieve your recruitment using Contact and Company custom field. So using company custom field you can add one contact to many companies. Below is the example :- 

http://snag.gy/0nAzB.jpg

http://snag.gy/r6rYN.jpg

Use below API with json data : 

https://github.com/agilecrm/rest-api#14-update-properties-of-a-contact-by-id-partial-update

`{
    "id": "5677611220992000",
    "properties": [
        {
            "name": "Companies List",
            "type": "CUSTOM",
            "value": "[\"5189192371929088\",\"5640887774216192\"]"
        },
        {
            "type": "SYSTEM",
            "name": "first_name",
            "value": "Daniel"
        },
        {
            "type": "SYSTEM",
            "name": "last_name",
            "value": "Thrath"
        },
        {
            "name": "email",
            "value": "daniel@trath.com",
            "subtype": ""
        }
    ]
}`

Please contact Agile CRM support team if you need any information.

Thanks

**Comment by arekpien** [comment]
Hello @arekpien,
Is it possible somehow to show users belong to company (In company context ->Contacts) whose have been added this way?

**Comment by graut** [comment]
Hi @arekpien 

Yes this is possible and it same as contact has many companies. Just json data will be change.

https://github.com/agilecrm/rest-api#22-updating-a-company

`{
    "id": 5651082298523648,
    "properties": [
        {
            "type": "SYSTEM",
            "name": "name",
            "value": "Spicejet"
        },
        {
            "type": "SYSTEM",
            "name": "url",
            "value": "http://www.spicejet.com/"
        },
        {
            "name": "website",
            "value": "http://www.linkedin.com/company/agile-crm",
            "subtype": "LINKEDIN"
        },
        {
            "name": "Contact List related to a company",
            "type": "CUSTOM",
            "value": "[\"5189192371929088\",\"5640887774216192\"]"
        }
    ]
}`

And create one contact custom field in the company tab.

http://snag.gy/uFXQ6.jpg

Please contact Agile CRM support team if need any other help

Thanks

**Comment by ranjanagilecrm** [comment]
Hi @arekPien ,

I checked it from REST API Client Tool for all the requests being mentioned above and i'm getting what was being expected. 

Please contact Agile CRM HELP DESK if you have any concerns.
