### ISSUE TITLE
Endpoint to retrieve a List of Companies is POST not GET

### ISSUE THREAD

**Issue by bowett** [agilecrm/rest-api#24]
In the README the method to retrieve a list of companies has GET listed as the Method...

> 2.3 Get list of companies
> dev/api/contacts/companies/list
> Method: GET

This is what I would expect but I get a 405 Error with this. It only works if I call it as a POST which is very counterintuitive.

**Comment by graut** [comment]
Hi @bowett,

We have modified text to POST. Thank you for pointing out.

In curl request we had POST but description it was 'GET' by mistake.

Please let us know in case need further information.

Thanks

**Comment by bowett** [comment]
Thanks, still seems counterintuitive to have it as a POST when it's retrieving a list of things but I appreciate that's a much bigger change and beyond the scope of this issue.
