### ISSUE TITLE
How to find contacts by tag?

### ISSUE THREAD

**Issue by wapgear** [agilecrm/rest-api#26]
Hello. It's possible to find contacts with tag **\* like in *agilecrm.com filter?
[Screenshot](https://pp.vk.me/c631922/v631922860/4051d/S7WnCKN7T4k.jpg)

**Comment by graut** [comment]
Hi @WapGeaR ,

Yes It is possible, Please use below API call

Request URL:  https://ghanshyam.agilecrm.com/dev/api/filters/filter/dynamic-filter
Request Method:POST
accept:application/json
content-type:application/json

FORM Data : 

page_size:25
global_sort_key:-created_time
filterJson:{"rules":[{"LHS":"tags","CONDITION":"EQUALS","RHS":"tester"}],"contact_type":"PERSON"}

Note : 
1 . Here "tags" is tag filter, You can use either Custom filed and System field also ("first_name","last_name","phone" etc), Make sure name of properties are case sensitive.
2 . "tester" is the value you are looking for with tags filter.
3. "-created_time" retrieve contact based on latest contact created first and "created_time" older first. 


 We have sample example in PHP and C# please let us know if you need any language implementation.

**Comment by WapGeaR** [comment]
@graut, wow, thanks for very fast answer.
I'll try it now on NodeJS :)

**Comment by WapGeaR** [comment]
@graut hm, i got 500 error:

`
{ data: 
   { status: '500',
     'exception message': 'java.lang.NullPointerException' },
  status: 500,
  statusText: 'Internal Server Error',
`

**Comment by graut** [comment]
Hi @WapGeaR ,

Sorry my mistake, content type should be "application/x-www-form-urlencoded"

accept: application/json
content-type: application/x-www-form-urlencoded

Tested API call

https://snag.gy/u9pR35.jpg

Please check our code in node.js at below link.

https://github.com/agilecrm/nodejs/blob/master/README.md#52-get-contacts-or-companies-by-tag

Please let us know in case need further information.

Thanks

**Comment by ranjanagilecrm** [comment]
Hi @wapgear,

Hope the above mentioned steps fixed your issue. 

Since the issue was raised long back, I tested it once again to make sure everything is working fine as per the design.   

Please let us know in case need further information.

**Comment by jsl15c** [comment]
This functionality does not appear to work in PHP implementation
