### ISSUE TITLE
Count not in first contact

### ISSUE THREAD

**Issue by mbaxter91288** [agilecrm/rest-api#27]
Hi,

I've used the `page_size` param to paginate my results. The documentation states: "Count of the contacts will be in the first contact...". This is not within the first contact of the results. I have 3 contacts in my CRM and requesting 1 per page like so:

`https://commotioncreative.agilecrm.com/dev/api/contacts?page_size=1`

However now `count` value is visible in the returned contact. I can see the `cursor` to retrieve the next page.

Please advise.

**Comment by graut** [comment]
Hi @mbaxter91288,

Currently we have removed variable named count for get list of contacts. As we don't need count for listing contacts as it was doing extra call and making performance slow we removed this variable.  

Please check our below two videos which explain how to use paging technique to list out contacts.

1. https://www.youtube.com/watch?v=2Yui9HJXAOE

 2. https://www.youtube.com/watch?v=jJAAZKqybQ4

Please note that if in case you need to know contact count, you can use below API.

https://{your_domain}.agilecrm.com/dev/api/contacts/list/count
Method : GET
accept : application/json

Please let us know in case need further information.

Thanks

**Comment by mbaxter91288** [comment]
Perfect thank you for the information and the videos!
