### ISSUE TITLE
City and state names

### ISSUE THREAD

**Issue by bfarayev** [agilecrm/rest-api#29]
Probably state and city names should be switched here:

```
{
      "type": "SYSTEM",
      "name": "address",
      "value": "{\"zip\":\"2000\",\"address\":\"225 George Street\",\"state\":\"Sydney\",\"countryname\":\"Australia\",\"country\":\"AU\",\"city\":\"NSW\"}"
}
```

**Comment by ranjanagilecrm** [comment]
Hi @bfarayev ,

The state and city names are already present in the same manner you mentioned above. Please check the below Github link for more details :
https://github.com/agilecrm/rest-api#properties-json

Please contact Agile CRM Customer Support if you need more information.
