### ISSUE TITLE
Contact update broken?

### ISSUE THREAD

**Issue by nozpheratu** [agilecrm/rest-api#3]
The contact update routing seems to be broken? Or perhaps I'm misunderstanding it's use. It doesn't seem to accept an id in the route in the same fashion that GET contact by ID would, I get a 405 if I try using a similar route but with PUT instead of GET of course.

I also tried the "dev/api/contact" endpoint and passing ID or email as a data argument as suggested in the docs. It returned a 200, but nothing seems to happen.

**Comment by graut** [comment]
It looks like wrong curl used
Wrong curl used
curl https://mycompany.agilecrm.com/dev/api/contacts/5735995932672000 -H "Accept :application/xml" -v \
-u "test@example.com  :xxxx" -d '{"tags":["foo"] }' -X PUT

Correct is:
curl https://{domain}.agilecrm.com/dev/api/contacts -H "Content-Type: application/json" -d { "id": 5662005255995392,"tags": ["Lead1","LikelyBuyer1"]} "  -v -u test@example.com:4uet78u6atfn38m9dounnq9g4u -X PUT

**Comment by ranjanagilecrm** [comment]
Hi @nozpheratu,

GET & PUT are http methods used to retrieve the data and update the data respectively. We are using these methods based on our requirement. 

If you want to retrieve the contact details then pass the contact id in the request using GET  method.
Similarly,  if you want to update the  properties of a contact then send the JSON data (the properties of a contact you want to update) inside the body.
