### ISSUE TITLE
Typing Question for Values

### ISSUE THREAD

**Issue by ghost** [agilecrm/rest-api#30]
I have a question about value types.

I noticed in one of the examples for contact fields there's a "created" field that has an int JSON type, while in the docs it says "value" will always be a string. Is it really picky or can I just use strings for all values assuming the API will handle it on the other side?

I'm using D to handle these responses so I have to critique every detail that can derail incoming response handling.

**Comment by graut** [comment]
You can use string for all values.
Thanks

**Comment by clintonskakun** [comment]
Thanks for the quick answer!
