### ISSUE TITLE
Deleting a deal response code

### ISSUE THREAD

**Issue by bfarayev** [agilecrm/rest-api#32]
Response code 200-OK for deleting a deal isn't valid. It should be changed to 204.

**Comment by graut** [comment]
Yes @bfarayev  status code should be 204 for DELETE API. Updated docs with 204

Thanks

**Comment by bfarayev** [comment]
Fixed with https://github.com/agilecrm/rest-api/commit/2879e8f5615c6155802a56422749c34d79668b76

Closing..
