### ISSUE TITLE
Add Call Log through email

### ISSUE THREAD

**Issue by lucakuehne** [agilecrm/rest-api#33]
Please add the posibility to add call logs trough the API! And let us change the date when the call log has been added/when the call has been done.

**Comment by ranjanagilecrm** [comment]
Hi,
Please use below API to create call logs through API!

1> For Inbound Call:
Request URL:https://{domain}.agilecrm.com/dev/api/notes
Request Method:POST 
Accept : application/json
Content-Type : application/json

For inbound call below is the json format:
{
    "subject": "Test Incoming Call",
    "callType": "inbound",
    "hour": "0",
    "min": "3",
    "sec": "30",
    "description": "Hi !",
    "contact_ids": [
        "5736126123868160"
    ],
    "status": "answered",
    "phone": "+918886363277",
    "duration": 210
}


2> For Outbound Call:
Request URL:https://{domain}.agilecrm.com/dev/api/notes
Request Method:POST 
Accept : application/json
Content-Type : application/json

For outbound call below is the json format:
{
    "subject": "Outgoing Call",
    "callType": "outbound",
    "hour": "0",
    "min": "3",
    "sec": "30",
    "description": "Hi!",
    "contact_ids": [
        "5746821397741568"
    ],
    "status": "answered",
    "phone": "+918886363277",
    "duration": 210
}


Notes:
Possible values for 'status' are as follows:
1> answer
2> no-answer
3> failed
4> voicemail
5> missed
6> inquiry
7> interest
8> no interest
9> incorrect referral
10> meeting scheduled
11> new opportunity

Please let me know in case need any further information

**Comment by lucakuehne** [comment]
@ranjanagilecrm This looks like a solution that could work. But like this it would add the call log right now in the timeline of the contact. Please let us add a call log from a call which I did on the 02.04.2016 as an example.

**Comment by ranjanagilecrm** [comment]
Hi @lucakuehne ,

Sorry for late reply ! Currently we don't have any option to create a call log using date via API. We are using the existing time to create a call log via Dashboard and the same way we can do it via API.

**Comment by TomKaltz** [comment]
@ranjanagilecrm @agilecrm Is it on the roadmap to be able to back-date a call log.  It would be useful for importing old call logs.
