### ISSUE TITLE
How can I access all messages within a ticket?

### ISSUE THREAD

**Issue by nathanaeljones** [agilecrm/rest-api#34]
It would appear from the documentation that only the last response/reply for a ticket are available through the API. Is this correct?

**Comment by ranjanagilecrm** [comment]
Hi Nathan,

We can access all the messages within a ticket by below approach using REST API :
https://{domain}.agilecrm.com/dev/api/tickets/notes/{ticketid} 

Method: GET
Accepts: application/json

Will update the Github document accordingly.

Thanks & Regards,
Ranjan

**Comment by ranjanagilecrm** [comment]
Hi,

We can access all the messages within a ticket by below approach using REST API :
https://{domain}.agilecrm.com/dev/api/tickets/notes/{ticketid}

Method: GET
Accepts: application/json

Will update the Github document accordingly.

Thanks & Regards,
Ranjan

**Comment by ranjanagilecrm** [comment]
API added to get all the messages  within a ticket. Hence, updated the document accordingly
