### ISSUE TITLE
Can't upload file on Agile cloud from my local machine

### ISSUE THREAD

**Issue by pakol123** [agilecrm/rest-api#35]
I have written code to upload file from local machine to cloud in VBA and its working fine. But when I see documents in my Agile account, I can still see my local file address linked to uploaded document. I also can't download this file.
Can anyone please help for the same..

**Comment by ranjanagilecrm** [comment]
Hi @pakol123 ,

Sorry to say that we are not supporting the feature you're asking for.  

Please let us know in case need further information.
