### ISSUE TITLE
Need an endpoint to get all contact's custom fileds

### ISSUE THREAD

**Issue by nadeemzai** [agilecrm/rest-api#36]
Hi i want to integrate agilecem sales with my site , and now i need an endpoint to get all contact's custom fileds, so that i can send custom fileds values from my site to my agilecrm account.

**Comment by dedupely** [comment]
This would be a nice feature for me as well. Right now we need to guess the custom fields by extracting them from each contact. However, this doesn't leave room for when someone deletes a custom field.

**Comment by ranjanagilecrm** [comment]
Hi @nadeemzai , @dedupely 

You can get all contact's custom fields by the below endpoint :

**Request :**
Endpoint URL :  https://{domain}.agilecrm.com/core/api/custom-fields/scope?scope=CONTACT
Method : GET
Accept : application/json

**Response:**
Status 200 : Gives all the custom fields related to contact

Sample JSON Data you'll get in the response :
{
"id": 5647262914969600,
"field_type": "TEXT",
"version": "v2",
"field_label": "TestCustomField",
"field_description": "TestCustomField",
"field_data": "",
"is_required": false,
"searchable": true,
"showInFilter": true,
"search_key": "TestCustomField",
"scope": "CONTACT",
"position": 2
},

In addition to this, you can also get all the custom fields related to companies and deals. Only you need to change the scope in the endpoint URL as mentioned below:
1. scope=COMPANY to get all the custom fields related to company
2. scope=DEAL to get all the custom fields related to deal


Please contact Agile CRM Customer Support if you need more information.
