### ISSUE TITLE
Update contact with email ID

### ISSUE THREAD

**Issue by maheshrestha** [agilecrm/rest-api#37]
Hi there,
Is there any way to update contact properties with email ID provided? I know there is an endpoint to edit contact with ID but in my system there is no way to get Id of the contact in Agile and there is no way to get response from API call as well.

**Comment by ranjanagilecrm** [comment]
Hi,
There is no way we can update contact properties with email ID provided. We need to send the Contact-Id of the contact to identify it rather then email ID.

Regards,
rrswain
