### ISSUE TITLE
How do re-assign emails and stats?

### ISSUE THREAD

**Issue by dedupely** [agilecrm/rest-api#38]
Are emails and stats linked by the email address of the contact? If I change an email to another contact, those emails and stats will show in that other contact? Basically, I'm trying to move emails and stats to another user.

**Comment by ranjanagilecrm** [comment]
Hi @dedupely ,

Re-assigning/changing an email of one contact to another contact is not possible. We don't have any API to reassign an email of a contact to another contact. 

Please contact Agile CRM Customer Support if you have any concerns.
