### ISSUE TITLE
Can I reassign another contact to an existing campaign?

### ISSUE THREAD

**Issue by dedupely** [agilecrm/rest-api#39]
This is what I want to do:

Delete a given contact with a campaign.
Move that contact's info to another contact, and re-assign the campaign to the new contact.

**Comment by ranjanagilecrm** [comment]
Hi @dedupley,

You can reassign another contact to an existing campaign but you need to make 2 API calls :

1> First you need to remove the contact with a campaign by using the below API :
     Remove contact from a campaign (https://github.com/agilecrm/rest-api#119-remove-contact-from-a-
     campaign)

2> And then you need to add another contact to an  existing campaign by using the below API: 
     Add contact to a campaign (https://github.com/agilecrm/rest-api#118-add-contact-to-a-campaign)
    
Please let us know in case need further information.
