### ISSUE TITLE
Adding tags to contacts doesn't seem to work either?

### ISSUE THREAD

**Issue by nozpheratu** [agilecrm/rest-api#4]
`https://{domain}.agilecrm.com/dev/api/contacts/bulk/tags` doesn't work? It's giving me 

> 404 Could not find resource

Same as #3

**Comment by ranjanagilecrm** [comment]
Hi @nozpheratu,

It looks like wrong request used for adding tags to contact. You can use the below request for adding tags to contacts:

Request : https://{domain}.agilecrm.com/dev/api/contacts  
Method: PUT
Content-Type: application/json
Body:
       { 
        "id": 5759084401786880,
        "tags": ["Lead1","LikelyBuyer1"]
       }

Using CURL:
https://{domain}.agilecrm.com/dev/api/contacts -H "Content-Type: application/json" -d { "id": 5662005255995392,"tags": ["Lead1","LikelyBuyer1"]} " -v -u test@example.com:4uet78u6atfn38m9dounnq9g4u -X PUT

In addition to this, i need to mention here is that you can also add tags to a contact based on email. For more details please go through the below link : 
https://github.com/agilecrm/rest-api#112-adding-tags-to-a-contact-based-on-email

Please get in touch with me in case you need further information
