### ISSUE TITLE
Tags not updating on contact update

### ISSUE THREAD

**Issue by dedupely** [agilecrm/rest-api#42]
The tags key in the contact object appears to not work.

**Comment by dedupely** [comment]
I found a fix. Need to use the alternative endpoint.

**Comment by sebastiencarceles** [comment]
Hi @dedupely , which endpoint did you use finally?

**Comment by dedupely** [comment]
The tags endpoint for updating contact tags. https://github.com/agilecrm/rest-api#17-update-tags-value-by-id
