### ISSUE TITLE
Dynamic Filters: Failed to complete request in 9490ms

### ISSUE THREAD

**Issue by dedupely** [agilecrm/rest-api#48]
I keep getting this error that the query timed out. At first I thought it was pulling too many contacts at once so I moved it to a 30 limit, but I still keep getting it randomly.

**Comment by agilecrm** [comment]
We are making some changes to the backends. This is especially the case if you are using Text Filter combinations and underlying Google is bailing out. Please stay tuned.

**Comment by dedupely** [comment]
Thanks for the update! I'm just filtering by contact type, updated and created times and order.
