### ISSUE TITLE
/contacts/search/email endpoint does not work

### ISSUE THREAD

**Issue by styks1987** [agilecrm/rest-api#5]
It seems all the items related to email and tags do not work. The two I have tried are 
/contacts/search/email and dev/api/contacts/email/tags/add
Response from the server 

HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 30 Dec 2014 14:30:09 GMT
< Server: Google Frontend
< Cache-Control: private
< Transfer-Encoding: chunked

**Comment by ranjanagilecrm** [comment]
Hi @styks1987,

Both the endpoints **dev/api/contacts/search/email**  & **dev/api/contacts/email/tags/add** to search a contact by email and to add tags to a contact based on email are working fine respectively. You can search the contact by email in 2 ways as mentioned below:

1> Request : dev/api/contacts/search/email/{email} 
     Method: GET

2> Request : dev/api/contacts/search/email
     Method : POST

This endpoint also works if you are going to search contact by email through JAVA API.
