### ISSUE TITLE
Provide better documentation

### ISSUE THREAD

**Issue by jqn** [agilecrm/rest-api#57]
First of all thanks for the API, but in the essence of saving Developers time the documentation could be improved:

For instance there is very little information about how to use filters and which filters are available.
How would you traverse something like this to get "campaign_name"
```
     "campaignStatus": [
            {
                "start_time": 1529369387034,
                "end_time": 1529369465985,
                "campaign_id": "5204474519879680",
                "campaign_name": "New Contact",
                "status": "5204474519879680-DONE"
            },
            {
                "start_time": 1529369389927,
                "end_time": 1529369394511,
                "campaign_id": "5726971199750144",
                "campaign_name": "Web Lead",
                "status": "5726971199750144-DONE"
            }
        ],
```
the following doesn't work
```
{"rules":[{"LHS":"campaign_name","CONDITION":"EQUALS","RHS":"New Contact"}],"contact_type":"PERSON"}
```
the following works and it was just a wild guess
```
{"rules":[{"LHS":"campaignStatus","LHS_NEW": "campaign_name",CONDITION":"EQUALS","RHS":"New Contact"}],"contact_type":"PERSON"}
```

By the way what does "LHS" and "RHS" mean and how do you format the rules?

Also something like this only takes unix time with milliseconds, seconds won't work

```
{"rules":[{"LHS":"created_time","CONDITION":"BETWEEN","RHS":1529301600000,"RHS_NEW":1529388000000}],"contact_type":"PERSON"}
```
And to list contacts in descending/ascending order

```
// Descending
global_sort_key=-created_time
// Ascending
global_sort_key=created_time
```
Documenting the previous would have saved a lot of time

**Comment by dtrinchero** [comment]
I agree with Joaquin, it would be very helpful having more documentation on Dynamic filters.
Is there a CONDiTION similar to SQL's Like?
