### ISSUE TITLE
Search for contacts by custom property

### ISSUE THREAD

**Issue by wizsilex** [agilecrm/rest-api#6]
Is there any way to search for users using a custom type property like user_id in my system, not ID from agilecrm?

**Comment by graut** [comment]
Please find content of 
https://github.com/agilecrm/rest-api#17-search-contactscompanies
This search method search contacts and companies based on keyword of custom field.

**Comment by ranjanagilecrm** [comment]
Hi @wizsilex ,

You can search the contacts based on the custom property you defined in Admin Settings.
Please ignore the previous content mentioned above as the content was being changed in Github document.  Find the below content for your query : 
https://github.com/agilecrm/rest-api#111-search-contactscompanies 

Request : https://{domain}.agilecrm.com/dev/api/search?q=TL001&page_size=10&type="PERSON"
where q=TL001 is the value for custom field (user_id) which is already being defined in Admin Settings.
Method :  GET
Accept : application/json
