### ISSUE TITLE
Reliably get all contacts

### ISSUE THREAD

**Issue by darrenklein** [agilecrm/rest-api#67]
Hello - I have nearly 6000 contacts in my Agile space, and I need to export them all, ideally via your REST API.  I've been making a GET request to `https://{domain}.agilecrm.com/dev/api/contacts?page_size=6000` but this consistently errors out because the query takes too long to execute - it seems to be capped at 60 seconds, and will throw the 500 error:

```
The server encountered an error and could not complete your request. Please try again in 30 seconds.
```

(queries with lower page sizes will work, but that doesn't really help me, I need them all)

Dumping them to a .csv file via a bulk operation in the dashboard is not sufficient, because I need the data from my contacts' "CUSTOM" fields, which is not included in the .csv export.

Can you advise me on how I can reliably export all of my contact data?

**Comment by paddie** [comment]
@darrenklein I darren, use around `200` for `page_size` and then use pagination. The last contact item in the list will contain a `cursor` item that you'll have to add as a queryString to your request.

Here's some python code that does it for both `get` and `post` requests:

```python
def __paginate(self, method, path, data=None, params=None, **kwargs):
        """paginates over items with a trailing item containing a cursor and passes arguments as either 'data' or 'params' depending on method"""
        while True:
            items = self.request(method, path, data=data, params=params, **kwargs)

            if not items:
                return

            # remove possible 'cursor' value from last item
            cursor = items[-1].pop("cursor", None)

            for item in items:
                yield item

            if not cursor:
                return

            if data:
                data["cursor"] = cursor
            elif params:
                params["cursor"] = cursor
```

**Comment by darrenklein** [comment]
Thanks for taking the time to help me out - I managed to find another way to do what I needed, but I appreciate your feedback - this will help me (and hopefully others) in the future.

**Comment by darrenklein** [comment]
Hey, just wanted to let you know that I finally had the opportunity to put this to good use.  Thanks again!
