### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#7]
Hello!

I'm working with your REST api right now and I've noticed there are no filtering options when fetching contacts.

Some useful additions would be:
GET dev/api/contacts?email=john@somecompany.com
(searching with a POST request? hmmm...)

GET dev/api/contacts?domain=somecompany.com

GET dev/api/contacts?first_name=John

GET dev/api/contacts?last_name=Doe

GET dev/api/contacts?company=somecompany

GET dev/api/contacts?type=PERSON (or COMPANY)

GET dev/api/contacts?tags=seller&tags=rich...

Really simple filters that would be a huge improvement for us end users. This way fetching contacts is cleaner, it's almost nonsense having to retrieve MBs of JSON files and parse them all the time (throwing away 99% and more of the data retrieved)

Also the JSON output would be way cleaner in the form:

{
    "count": 1238,
    "page_size": 40,
    "page_start": 39,
    "page_end": 79,
    "next_page": "ASd98asdh982hd98ahs",
    "results": [ ... ]
}

**Comment by graut** [comment]
First of all thanks for your suggestion and sorry for late reply to git hub issue :).

Regrading your first suggestion.

We have two rest api calls,

1.	POST method:-

 curl https://{domain}.agilecrm.com/dev/api/contacts/search/email -H "Accept: application/xml"
-H "Content-Type :application/x-www-form-urlencoded" 
-d ‘email_ids=["notifications@basecamp.com  "]’
-v -u {email}:{apikey} -X POST

This rest call we are using to get multiple contacts by sending multiple email ids using post method.
  2.GET method

https://{domain}.agilecrm.com/dev/api/contacts/search/email/abc@def.com

Note: We will update second method i.e get rest api soon to api docs.

And for issue:-
Issue:
1. GET dev/api/contacts?domain=somecompany.com
2. GET dev/api/contacts?first_name=John
3. GET dev/api/contacts?last_name=Doe
4. GET dev/api/contacts?company=somecompany
5. GET dev/api/contacts?type=PERSON (or COMPANY)
6. GET dev/api/contacts?tags=seller&tags=rich...

Please find the contents of 
https://github.com/agilecrm/rest-api#17-search-contactscompanies

We have method which search contacts and companies by keywords of default fields and searchable custom fields.This can help us to resolve your doubt and suggestion.

We are keep working to reply all git hub issue.
Thanks once again for your valuable suggestion. :)

**Comment by andreafdaf** [comment]
Hi! This is a more than welcome upgrade on this API

Searching by domain is not yet supported but we are getting close :)
