### ISSUE TITLE
API errors don't follow the Accept header

### ISSUE THREAD

**Issue by andreafdaf** [agilecrm/rest-api#8]
When I ask for JSON output I clearly expect to receive a JSON both if the reponse is successful or an error, instead I receive a string which is not parseable and forces me to double-check all data I get back from you. This should be fixed!

**Comment by clintonskakun** [comment]
i agree. Having an api that's suppose to return one type of response makes things extremely dangerous when it randomly returns html on a server error response.

**Comment by ranjanagilecrm** [comment]
Hi,

Please give some scenario where API errors don't follow the Accept header so that we can check.

**Comment by andreafdaf** [comment]
Try making a request with a body and set a wrong 'Content-Length' header value.
I just tried adding a contact setting the content length to 3, the response is:
```
Unexpected end-of-input in field name
 at [Source: com.google.apphosting.runtime.jetty.RpcConnection$RpcRequestInput@7ff8e011; line: 1, column: 9]
```
Which is a string, whilst I'm explicitly saying that I accept JSON
